### ISSUE TITLE
Back button still navigates away from page within the site. 

### ISSUE THREAD

**Issue by Ben-Pattinson** [ShaunCurtis/Blazor.Database#1]
Firstly, must say that I love the simplicity of this approach. I was eyeing you previous navigation based approach with some trepidation. However. This doesn't seem to stop users click back in the browser and navigating away. Is this intentional? 

I'd suggest a small change to the JavaScript: 

**var _navigateLockOn = false;
var navigateAwayMessage = "There are unsaved changes on this page.  Do you want to leave?";**
window.cecblazor_setEditorExitCheck = function (show) {
    if (show) {
        **_navigateLockOn = true;**
        window.addEventListener("beforeunload", cecblazor_showExitDialog);
    }
    else {
        **_navigateLockOn = false;**
        window.removeEventListener("beforeunload", cecblazor_showExitDialog);
    }
}

window.cecblazor_showExitDialog = function (event) {
    event.preventDefault();
    event.returnValue = navigateAwayMessage;
    }

**window.onload = function () {
        if (window.history && history.pushState) {            
                if (history.state == null) {
                    history.pushState({'status': 'ongoing'}, null, null);
                }
            window.onpopstate = function (event) {
                if (_navigateLockOn) {
                    const endProgress = confirm(navigateAwayMessage);
                    if (endProgress) {
                        window.onpopstate = null;
                        history.back();
                    } else {
                        history.pushState(null, document.title, location.href);
                    }
                }
                else {
                    window.onpopstate = null;
                    history.back();
                }
            };            
        }**
    };

**Comment by ShaunCurtis** [comment]
I'm away travelling at the moment, will have a look and sort this weekend.

**Comment by ShaunCurtis** [comment]
I've been working on solutions to this problem for a while.  Manipulating the history is one option, but I wasn't really happy with it.

Anyway, to cut a long story short, I was doing some work on my custom RouteView component when a light came on.  If you check out the demo site you can see the new solution in action.  There are a few tweaks to the inline and dialog versions to rewind that I needed to solve.  Note, I'm still tweaking the code and the whole Database project and haven't updated the articles/documentation yet.
